// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaskislaAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20211201112203_WithDataAndRoles")]
    partial class WithDataAndRoles
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Marriage", b =>
                {
                    b.Property<int>("MarriageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarriageId"), 1L, 1);

                    b.Property<int>("female")
                        .HasColumnType("int");

                    b.Property<int>("male")
                        .HasColumnType("int");

                    b.HasKey("MarriageId");

                    b.ToTable("marriages");
                });

            modelBuilder.Entity("Entities.Models.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gender");

                    b.Property<bool?>("IsLiving")
                        .HasColumnType("bit")
                        .HasColumnName("is_living");

                    b.Property<string>("LastName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("last_name");

                    b.Property<int?>("father")
                        .HasColumnType("int")
                        .HasColumnName("father");

                    b.Property<int?>("mother")
                        .HasColumnType("int")
                        .HasColumnName("mother");

                    b.HasKey("id");

                    b.ToTable("persons", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 2,
                            mother = 3
                        },
                        new
                        {
                            id = 2,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 8,
                            mother = 9
                        },
                        new
                        {
                            id = 3,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 26,
                            mother = 27
                        },
                        new
                        {
                            id = 5,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 13,
                            mother = 14
                        },
                        new
                        {
                            id = 6,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 2,
                            mother = 3
                        },
                        new
                        {
                            id = 7,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 2,
                            mother = 3
                        },
                        new
                        {
                            id = 8,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "lastname",
                            father = 85,
                            mother = 86
                        },
                        new
                        {
                            id = 9,
                            FirstName = "John",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "Johnson",
                            father = 94,
                            mother = 87
                        },
                        new
                        {
                            id = 10,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 8,
                            mother = 9
                        },
                        new
                        {
                            id = 11,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 8,
                            mother = 9
                        },
                        new
                        {
                            id = 12,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 8,
                            mother = 9
                        },
                        new
                        {
                            id = 13,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 22,
                            mother = 23
                        },
                        new
                        {
                            id = 14,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 18,
                            mother = 19
                        },
                        new
                        {
                            id = 15,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 13,
                            mother = 14
                        },
                        new
                        {
                            id = 16,
                            FirstName = "John",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 13,
                            mother = 14
                        },
                        new
                        {
                            id = 17,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 13,
                            mother = 14
                        },
                        new
                        {
                            id = 18,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 95,
                            mother = 98
                        },
                        new
                        {
                            id = 19,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 93,
                            mother = 92
                        },
                        new
                        {
                            id = 20,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 18,
                            mother = 19
                        },
                        new
                        {
                            id = 21,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 18,
                            mother = 19
                        },
                        new
                        {
                            id = 22,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 186,
                            mother = 188
                        },
                        new
                        {
                            id = 23,
                            FirstName = "John",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            id = 24,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 22,
                            mother = 23
                        },
                        new
                        {
                            id = 25,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 22,
                            mother = 78
                        },
                        new
                        {
                            id = 26,
                            FirstName = "Mary",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "Ilyasoglu",
                            father = 88,
                            mother = 89
                        },
                        new
                        {
                            id = 27,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 90,
                            mother = 91
                        },
                        new
                        {
                            id = 28,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 26,
                            mother = 27
                        },
                        new
                        {
                            id = 29,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 26,
                            mother = 27
                        },
                        new
                        {
                            id = 30,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 26,
                            mother = 27
                        },
                        new
                        {
                            id = 31,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 26,
                            mother = 27
                        },
                        new
                        {
                            id = 32,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 81,
                            mother = 11
                        },
                        new
                        {
                            id = 33,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 81,
                            mother = 11
                        },
                        new
                        {
                            id = 34,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 81,
                            mother = 11
                        },
                        new
                        {
                            id = 35,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 10,
                            mother = 54
                        },
                        new
                        {
                            id = 36,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 10,
                            mother = 54
                        },
                        new
                        {
                            id = 37,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 53,
                            mother = 12
                        },
                        new
                        {
                            id = 38,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 53,
                            mother = 12
                        },
                        new
                        {
                            id = 39,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 53,
                            mother = 12
                        },
                        new
                        {
                            id = 40,
                            FirstName = "Mary",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 55,
                            mother = 31
                        },
                        new
                        {
                            id = 41,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 55,
                            mother = 31
                        },
                        new
                        {
                            id = 42,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 55,
                            mother = 31
                        },
                        new
                        {
                            id = 43,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 30,
                            mother = 56
                        },
                        new
                        {
                            id = 44,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 30,
                            mother = 56
                        },
                        new
                        {
                            id = 45,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 30,
                            mother = 56
                        },
                        new
                        {
                            id = 46,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 57,
                            mother = 28
                        },
                        new
                        {
                            id = 47,
                            FirstName = "Mary",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 57,
                            mother = 28
                        },
                        new
                        {
                            id = 48,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 57,
                            mother = 28
                        },
                        new
                        {
                            id = 49,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 58,
                            mother = 29
                        },
                        new
                        {
                            id = 50,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 58,
                            mother = 29
                        },
                        new
                        {
                            id = 51,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 58,
                            mother = 29
                        },
                        new
                        {
                            id = 53,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 193,
                            mother = 194
                        },
                        new
                        {
                            id = 54,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte"
                        },
                        new
                        {
                            id = 56,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu"
                        },
                        new
                        {
                            id = 57,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "achternam"
                        },
                        new
                        {
                            id = 58,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 116
                        },
                        new
                        {
                            id = 59,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "lastname"
                        },
                        new
                        {
                            id = 60,
                            FirstName = "John",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            id = 61,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 197,
                            mother = 198
                        },
                        new
                        {
                            id = 62,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 59,
                            mother = 24
                        },
                        new
                        {
                            id = 63,
                            FirstName = "Mary",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 59,
                            mother = 24
                        },
                        new
                        {
                            id = 64,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 20,
                            mother = 84
                        },
                        new
                        {
                            id = 65,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 21,
                            mother = 61
                        },
                        new
                        {
                            id = 66,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 21,
                            mother = 61
                        },
                        new
                        {
                            id = 67,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            id = 68,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 67,
                            mother = 42
                        },
                        new
                        {
                            id = 69,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 67,
                            mother = 42
                        },
                        new
                        {
                            id = 70,
                            FirstName = "Mary",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "Ilyasoglu",
                            father = 67,
                            mother = 42
                        },
                        new
                        {
                            id = 71,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam"
                        },
                        new
                        {
                            id = 72,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad"
                        },
                        new
                        {
                            id = 73,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 40,
                            mother = 71
                        },
                        new
                        {
                            id = 74,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 75,
                            mother = 32
                        },
                        new
                        {
                            id = 75,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 76,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte"
                        },
                        new
                        {
                            id = 77,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 62,
                            mother = 83
                        },
                        new
                        {
                            id = 78,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam"
                        },
                        new
                        {
                            id = 79,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 80,
                            mother = 25
                        },
                        new
                        {
                            id = 80,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "lastname"
                        },
                        new
                        {
                            id = 81,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 142,
                            mother = 120
                        },
                        new
                        {
                            id = 82,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 83,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte"
                        },
                        new
                        {
                            id = 84,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu"
                        },
                        new
                        {
                            id = 85,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "achternam",
                            father = 110
                        },
                        new
                        {
                            id = 86,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "soyad"
                        },
                        new
                        {
                            id = 87,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "lastname"
                        },
                        new
                        {
                            id = 88,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "Johnson"
                        },
                        new
                        {
                            id = 89,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 90,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "Rutte",
                            father = 96,
                            mother = 97
                        },
                        new
                        {
                            id = 91,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "Ilyasoglu"
                        },
                        new
                        {
                            id = 92,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "achternam"
                        },
                        new
                        {
                            id = 93,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "soyad"
                        },
                        new
                        {
                            id = 94,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "lastname"
                        },
                        new
                        {
                            id = 95,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "Johnson"
                        },
                        new
                        {
                            id = 96,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 97,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "Rutte"
                        },
                        new
                        {
                            id = 98,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "Ilyasoglu"
                        },
                        new
                        {
                            id = 99,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "achternam",
                            father = 85,
                            mother = 86
                        },
                        new
                        {
                            id = 100,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "soyad",
                            father = 85,
                            mother = 101
                        },
                        new
                        {
                            id = 101,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "lastname"
                        },
                        new
                        {
                            id = 102,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 93,
                            mother = 92
                        },
                        new
                        {
                            id = 103,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 93,
                            mother = 92
                        },
                        new
                        {
                            id = 104,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "Rutte",
                            father = 93,
                            mother = 92
                        },
                        new
                        {
                            id = 105,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 102,
                            mother = 109
                        },
                        new
                        {
                            id = 106,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 102,
                            mother = 109
                        },
                        new
                        {
                            id = 107,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 102,
                            mother = 109
                        },
                        new
                        {
                            id = 108,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 102,
                            mother = 109
                        },
                        new
                        {
                            id = 109,
                            FirstName = "John",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            id = 110,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 111,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 90,
                            mother = 91
                        },
                        new
                        {
                            id = 112,
                            FirstName = "Mary",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 90,
                            mother = 91
                        },
                        new
                        {
                            id = 113,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 90,
                            mother = 91
                        },
                        new
                        {
                            id = 114,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 90,
                            mother = 91
                        },
                        new
                        {
                            id = 115,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 90,
                            mother = 91
                        },
                        new
                        {
                            id = 116,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "Johnson"
                        },
                        new
                        {
                            id = 117,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 118,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 117,
                            mother = 150
                        },
                        new
                        {
                            id = 119,
                            FirstName = "Mary",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 117,
                            mother = 150
                        },
                        new
                        {
                            id = 120,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 117,
                            mother = 150
                        },
                        new
                        {
                            id = 121,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 117,
                            mother = 150
                        },
                        new
                        {
                            id = 122,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 117,
                            mother = 150
                        },
                        new
                        {
                            id = 123,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 119,
                            mother = 141
                        },
                        new
                        {
                            id = 124,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 119,
                            mother = 141
                        },
                        new
                        {
                            id = 125,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 119,
                            mother = 141
                        },
                        new
                        {
                            id = 126,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 118,
                            mother = 140
                        },
                        new
                        {
                            id = 127,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 118,
                            mother = 140
                        },
                        new
                        {
                            id = 128,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 118,
                            mother = 140
                        },
                        new
                        {
                            id = 129,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 118,
                            mother = 140
                        },
                        new
                        {
                            id = 130,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 139,
                            mother = 121
                        },
                        new
                        {
                            id = 131,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 139,
                            mother = 121
                        },
                        new
                        {
                            id = 132,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 139,
                            mother = 121
                        },
                        new
                        {
                            id = 133,
                            FirstName = "Mary",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 139,
                            mother = 121
                        },
                        new
                        {
                            id = 134,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 138,
                            mother = 122
                        },
                        new
                        {
                            id = 135,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 138,
                            mother = 122
                        },
                        new
                        {
                            id = 136,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 138,
                            mother = 122
                        },
                        new
                        {
                            id = 137,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 138,
                            mother = 122
                        },
                        new
                        {
                            id = 138,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 139,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 99
                        },
                        new
                        {
                            id = 140,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu"
                        },
                        new
                        {
                            id = 141,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam"
                        },
                        new
                        {
                            id = 142,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad"
                        },
                        new
                        {
                            id = 143,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 117,
                            mother = 150
                        },
                        new
                        {
                            id = 144,
                            FirstName = "John",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 117,
                            mother = 150
                        },
                        new
                        {
                            id = 145,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 146,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Rutte"
                        },
                        new
                        {
                            id = 147,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 142,
                            mother = 120
                        },
                        new
                        {
                            id = 148,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 142,
                            mother = 120
                        },
                        new
                        {
                            id = 149,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 142,
                            mother = 120
                        },
                        new
                        {
                            id = 150,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "lastname"
                        },
                        new
                        {
                            id = 151,
                            FirstName = "John",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            id = 152,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 153,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 154,
                            mother = 155
                        },
                        new
                        {
                            id = 154,
                            FirstName = "Mary",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Ilyasoglu"
                        },
                        new
                        {
                            id = 155,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam"
                        },
                        new
                        {
                            id = 156,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "soyad",
                            father = 154,
                            mother = 155
                        },
                        new
                        {
                            id = 157,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "lastname",
                            father = 154,
                            mother = 155
                        },
                        new
                        {
                            id = 158,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 154,
                            mother = 155
                        },
                        new
                        {
                            id = 159,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 160,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Rutte"
                        },
                        new
                        {
                            id = 161,
                            FirstName = "Mary",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 159,
                            mother = 156
                        },
                        new
                        {
                            id = 162,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 160,
                            mother = 157
                        },
                        new
                        {
                            id = 163,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "soyad"
                        },
                        new
                        {
                            id = 164,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "lastname"
                        },
                        new
                        {
                            id = 165,
                            FirstName = "John",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            id = 166,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 167,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 203,
                            mother = 204
                        },
                        new
                        {
                            id = 168,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu"
                        },
                        new
                        {
                            id = 169,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "achternam"
                        },
                        new
                        {
                            id = 170,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad"
                        },
                        new
                        {
                            id = 171,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "lastname"
                        },
                        new
                        {
                            id = 172,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 177,
                            mother = 178
                        },
                        new
                        {
                            id = 173,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 177,
                            mother = 178
                        },
                        new
                        {
                            id = 174,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 177,
                            mother = 178
                        },
                        new
                        {
                            id = 175,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 177,
                            mother = 178
                        },
                        new
                        {
                            id = 176,
                            FirstName = "Jones",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 177,
                            mother = 178
                        },
                        new
                        {
                            id = 177,
                            FirstName = "Tim",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "soyad"
                        },
                        new
                        {
                            id = 178,
                            FirstName = "Thomas",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "lastname"
                        },
                        new
                        {
                            id = 179,
                            FirstName = "John",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Johnson",
                            father = 185,
                            mother = 184
                        },
                        new
                        {
                            id = 180,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong",
                            father = 185,
                            mother = 184
                        },
                        new
                        {
                            id = 181,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 185,
                            mother = 184
                        },
                        new
                        {
                            id = 182,
                            FirstName = "Mary",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 185,
                            mother = 184
                        },
                        new
                        {
                            id = 183,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "achternam",
                            father = 185,
                            mother = 184
                        },
                        new
                        {
                            id = 184,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "soyad",
                            father = 88,
                            mother = 89
                        },
                        new
                        {
                            id = 185,
                            FirstName = "Thomas",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "lastname"
                        },
                        new
                        {
                            id = 186,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "Johnson",
                            father = 187
                        },
                        new
                        {
                            id = 187,
                            FirstName = "Robin",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 188,
                            FirstName = "Jonathan",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "Rutte"
                        },
                        new
                        {
                            id = 189,
                            FirstName = "Mary",
                            Gender = "",
                            LastName = "Ilyasoglu",
                            father = 95,
                            mother = 98
                        },
                        new
                        {
                            id = 190,
                            FirstName = "Jones",
                            Gender = "",
                            LastName = "achternam",
                            father = 95,
                            mother = 98
                        },
                        new
                        {
                            id = 191,
                            FirstName = "Tim",
                            Gender = "",
                            LastName = "soyad",
                            father = 95,
                            mother = 98
                        },
                        new
                        {
                            id = 192,
                            FirstName = "Thomas",
                            Gender = "",
                            LastName = "lastname",
                            father = 95,
                            mother = 98
                        },
                        new
                        {
                            id = 193,
                            FirstName = "John",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Johnson"
                        },
                        new
                        {
                            id = 194,
                            FirstName = "Robin",
                            Gender = "F",
                            IsLiving = true,
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 195,
                            FirstName = "Jonathan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Rutte",
                            father = 193,
                            mother = 194
                        },
                        new
                        {
                            id = 196,
                            FirstName = "Mary",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Ilyasoglu",
                            father = 193,
                            mother = 194
                        },
                        new
                        {
                            id = 197,
                            FirstName = "Jones",
                            Gender = "M",
                            IsLiving = false,
                            LastName = "achternam"
                        },
                        new
                        {
                            id = 198,
                            FirstName = "Tim",
                            Gender = "F",
                            IsLiving = false,
                            LastName = "soyad"
                        },
                        new
                        {
                            id = 199,
                            FirstName = "Thomas",
                            Gender = "M",
                            LastName = "lastname",
                            father = 197,
                            mother = 198
                        },
                        new
                        {
                            id = 200,
                            FirstName = "John",
                            Gender = "",
                            LastName = "Johnson",
                            father = 197,
                            mother = 198
                        },
                        new
                        {
                            id = 203,
                            FirstName = "Robin",
                            Gender = "M",
                            LastName = "De Jong"
                        },
                        new
                        {
                            id = 204,
                            FirstName = "Jonathan",
                            Gender = "F",
                            LastName = "Rutte"
                        },
                        new
                        {
                            id = 205,
                            FirstName = "Mary",
                            Gender = "M",
                            LastName = "Ilyasoglu",
                            father = 203,
                            mother = 204
                        },
                        new
                        {
                            id = 206,
                            FirstName = "Jones",
                            Gender = "F",
                            LastName = "achternam",
                            father = 207,
                            mother = 192
                        },
                        new
                        {
                            id = 207,
                            FirstName = "Tim",
                            Gender = "M",
                            LastName = "soyad"
                        },
                        new
                        {
                            id = 208,
                            FirstName = "Thomas",
                            Gender = "",
                            LastName = "lastname",
                            father = 207,
                            mother = 192
                        },
                        new
                        {
                            id = 209,
                            FirstName = "John",
                            Gender = "",
                            LastName = "Johnson",
                            father = 207,
                            mother = 192
                        },
                        new
                        {
                            id = 210,
                            FirstName = "Robin",
                            Gender = "",
                            LastName = "De Jong",
                            father = 207,
                            mother = 192
                        },
                        new
                        {
                            id = 211,
                            FirstName = "Jonathan",
                            Gender = "",
                            LastName = "Rutte",
                            father = 212,
                            mother = 206
                        },
                        new
                        {
                            id = 212,
                            FirstName = "Mary",
                            Gender = "M",
                            LastName = "Ilyasoglu"
                        },
                        new
                        {
                            id = 213,
                            FirstName = "Jones",
                            Gender = "",
                            LastName = "achternam",
                            father = 212,
                            mother = 206
                        },
                        new
                        {
                            id = 214,
                            FirstName = "Tim",
                            Gender = "",
                            LastName = "soyad",
                            father = 212,
                            mother = 206
                        });
                });

            modelBuilder.Entity("Entities.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "7197feb0-05a3-4a99-a10b-9afd4ec06acc",
                            ConcurrencyStamp = "e184361c-edc0-4f49-b934-9c3e8b4e9657",
                            Name = "Visitor",
                            NormalizedName = "VISITOR"
                        },
                        new
                        {
                            Id = "f9c0cab9-0109-4d2f-8d24-594e9f0ff74b",
                            ConcurrencyStamp = "b833f2eb-6346-44d0-a706-f19061866a2e",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
