// <auto-generated />
using System;
using Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaskislaAPI.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20211129213541_WithMe")]
    partial class WithMe
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Entities.Models.Marriage", b =>
                {
                    b.Property<int>("MarriageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarriageId"), 1L, 1);

                    b.Property<int>("female")
                        .HasColumnType("int");

                    b.Property<int>("male")
                        .HasColumnType("int");

                    b.HasKey("MarriageId");

                    b.ToTable("marriages");
                });

            modelBuilder.Entity("Entities.Models.Person", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gender");

                    b.Property<bool?>("IsLiving")
                        .HasColumnType("bit")
                        .HasColumnName("is_living");

                    b.Property<string>("LastName")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("last_name");

                    b.Property<int?>("father")
                        .HasColumnType("int")
                        .HasColumnName("father");

                    b.Property<int?>("mother")
                        .HasColumnType("int")
                        .HasColumnName("mother");

                    b.HasKey("id");

                    b.ToTable("persons", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            FirstName = "Hasan",
                            Gender = "M",
                            IsLiving = true,
                            LastName = "Kurt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
